language: objective-c
osx_image: xcode11.6

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8

xcode_project: BPPhotoPicker.xcodeproj
xcode_scheme: PhotoPicker
xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone 11
